package styles

type VSCodeIcon struct {
	Name string
	Desc string
}

func (i VSCodeIcon) Title() string       { return i.Name }
func (i VSCodeIcon) Description() string { return i.Desc }
func (i VSCodeIcon) FilterValue() string { return i.Name }

var VSCodeIcons = []VSCodeIcon{
	{Name: "account", Desc: "Account icon"},
	{Name: "activate-breakpoints", Desc: "Activate breakpoints icon"},
	{Name: "add", Desc: "Add icon"},
	{Name: "alert", Desc: "Alert icon"},
	{Name: "archive", Desc: "Archive icon"},
	{Name: "array", Desc: "Array icon"},
	{Name: "arrow-both", Desc: "Arrow both directions icon"},
	{Name: "arrow-circle-down", Desc: "Arrow circle down icon"},
	{Name: "arrow-circle-left", Desc: "Arrow circle left icon"},
	{Name: "arrow-circle-right", Desc: "Arrow circle right icon"},
	{Name: "arrow-circle-up", Desc: "Arrow circle up icon"},
	{Name: "arrow-down", Desc: "Arrow down icon"},
	{Name: "arrow-left", Desc: "Arrow left icon"},
	{Name: "arrow-right", Desc: "Arrow right icon"},
	{Name: "arrow-small-down", Desc: "Small arrow down icon"},
	{Name: "arrow-small-left", Desc: "Small arrow left icon"},
	{Name: "arrow-small-right", Desc: "Small arrow right icon"},
	{Name: "arrow-small-up", Desc: "Small arrow up icon"},
	{Name: "arrow-swap", Desc: "Arrow swap icon"},
	{Name: "arrow-up", Desc: "Arrow up icon"},
	{Name: "azure-devops", Desc: "Azure DevOps icon"},
	{Name: "azure", Desc: "Azure icon"},
	{Name: "beaker-stop", Desc: "Beaker stop icon"},
	{Name: "beaker", Desc: "Beaker icon"},
	{Name: "bell", Desc: "Bell icon"},
	{Name: "bell-dot", Desc: "Bell with dot icon"},
	{Name: "bell-slash", Desc: "Bell slash icon"},
	{Name: "bell-slash-dot", Desc: "Bell slash with dot icon"},
	{Name: "bold", Desc: "Bold text icon"},
	{Name: "book", Desc: "Book icon"},
	{Name: "bookmark", Desc: "Bookmark icon"},
	{Name: "bracket-dot", Desc: "Bracket dot icon"},
	{Name: "bracket-error", Desc: "Bracket error icon"},
	{Name: "bracket", Desc: "Bracket icon"},
	{Name: "briefcase", Desc: "Briefcase icon"},
	{Name: "broadcast", Desc: "Broadcast icon"},
	{Name: "browser", Desc: "Browser icon"},
	{Name: "bug", Desc: "Bug icon"},
	{Name: "calendar", Desc: "Calendar icon"},
	{Name: "call-incoming", Desc: "Incoming call icon"},
	{Name: "call-outgoing", Desc: "Outgoing call icon"},
	{Name: "case-sensitive", Desc: "Case sensitive icon"},
	{Name: "check", Desc: "Check icon"},
	{Name: "check-all", Desc: "Check all icon"},
	{Name: "checklist", Desc: "Checklist icon"},
	{Name: "chevron-down", Desc: "Chevron down icon"},
	{Name: "chevron-left", Desc: "Chevron left icon"},
	{Name: "chevron-right", Desc: "Chevron right icon"},
	{Name: "chevron-up", Desc: "Chevron up icon"},
	{Name: "chip", Desc: "Chip icon"},
	{Name: "chrome-close", Desc: "Chrome close icon"},
	{Name: "chrome-maximize", Desc: "Chrome maximize icon"},
	{Name: "chrome-minimize", Desc: "Chrome minimize icon"},
	{Name: "chrome-restore", Desc: "Chrome restore icon"},
	{Name: "circle-filled", Desc: "Filled circle icon"},
	{Name: "circle-large-filled", Desc: "Large filled circle icon"},
	{Name: "circle-large-outline", Desc: "Large circle outline icon"},
	{Name: "circle-outline", Desc: "Circle outline icon"},
	{Name: "circle-slash", Desc: "Circle slash icon"},
	{Name: "circuit-board", Desc: "Circuit board icon"},
	{Name: "clear-all", Desc: "Clear all icon"},
	{Name: "clippy", Desc: "Clippy icon"},
	{Name: "clock", Desc: "Clock icon"},
	{Name: "clone", Desc: "Clone icon"},
	{Name: "close", Desc: "Close icon"},
	{Name: "close-all", Desc: "Close all icon"},
	{Name: "close-dirty", Desc: "Close dirty icon"},
	{Name: "cloud", Desc: "Cloud icon"},
	{Name: "cloud-download", Desc: "Cloud download icon"},
	{Name: "cloud-upload", Desc: "Cloud upload icon"},
	{Name: "code", Desc: "Code icon"},
	{Name: "coffee", Desc: "Coffee icon"},
	{Name: "collapse-all", Desc: "Collapse all icon"},
	{Name: "color-mode", Desc: "Color mode icon"},
	{Name: "combine", Desc: "Combine icon"},
	{Name: "comment", Desc: "Comment icon"},
	{Name: "comment-add", Desc: "Add comment icon"},
	{Name: "comment-discussion", Desc: "Comment discussion icon"},
	{Name: "comment-draft", Desc: "Comment draft icon"},
	{Name: "comment-unresolved", Desc: "Unresolved comment icon"},
	{Name: "compare-changes", Desc: "Compare changes icon"},
	{Name: "compass-active", Desc: "Active compass icon"},
	{Name: "compass-dot", Desc: "Compass dot icon"},
	{Name: "compass", Desc: "Compass icon"},
	{Name: "console", Desc: "Console icon"},
	{Name: "copilot", Desc: "Copilot icon"},
	{Name: "copy", Desc: "Copy icon"},
	{Name: "credit-card", Desc: "Credit card icon"},
	{Name: "dash", Desc: "Dash icon"},
	{Name: "dashboard", Desc: "Dashboard icon"},
	{Name: "database", Desc: "Database icon"},
	{Name: "debug-all", Desc: "Debug all icon"},
	{Name: "debug", Desc: "Debug icon"},
	{Name: "debug-alt", Desc: "Debug alternative icon"},
	{Name: "debug-alt-small", Desc: "Small debug alternative icon"},
	{Name: "debug-breakpoint", Desc: "Debug breakpoint icon"},
	{Name: "debug-breakpoint-conditional", Desc: "Conditional debug breakpoint icon"},
	{Name: "debug-breakpoint-conditional-disabled", Desc: "Disabled conditional debug breakpoint icon"},
	{Name: "debug-breakpoint-conditional-unverified", Desc: "Unverified conditional debug breakpoint icon"},
	{Name: "debug-breakpoint-data", Desc: "Data debug breakpoint icon"},
	{Name: "debug-breakpoint-data-disabled", Desc: "Disabled data debug breakpoint icon"},
	{Name: "debug-breakpoint-data-unverified", Desc: "Unverified data debug breakpoint icon"},
	{Name: "debug-breakpoint-disabled", Desc: "Disabled debug breakpoint icon"},
	{Name: "debug-breakpoint-function", Desc: "Function debug breakpoint icon"},
	{Name: "debug-breakpoint-function-disabled", Desc: "Disabled function debug breakpoint icon"},
	{Name: "debug-breakpoint-function-unverified", Desc: "Unverified function debug breakpoint icon"},
	{Name: "debug-breakpoint-log", Desc: "Log debug breakpoint icon"},
	{Name: "debug-breakpoint-log-disabled", Desc: "Disabled log debug breakpoint icon"},
	{Name: "debug-breakpoint-log-unverified", Desc: "Unverified log debug breakpoint icon"},
	{Name: "debug-breakpoint-unsupported", Desc: "Unsupported debug breakpoint icon"},
	{Name: "debug-breakpoint-unverified", Desc: "Unverified debug breakpoint icon"},
	{Name: "debug-console", Desc: "Debug console icon"},
	{Name: "debug-continue-small", Desc: "Small debug continue icon"},
	{Name: "debug-continue", Desc: "Debug continue icon"},
	{Name: "debug-coverage", Desc: "Debug coverage icon"},
	{Name: "debug-disconnect", Desc: "Debug disconnect icon"},
	{Name: "debug-hint", Desc: "Debug hint icon"},
	{Name: "debug-line-by-line", Desc: "Debug line by line icon"},
	{Name: "debug-pause", Desc: "Debug pause icon"},
	{Name: "debug-rerun", Desc: "Debug rerun icon"},
	{Name: "debug-restart", Desc: "Debug restart icon"},
	{Name: "debug-restart-frame", Desc: "Debug restart frame icon"},
	{Name: "debug-reverse-continue", Desc: "Debug reverse continue icon"},
	{Name: "debug-stackframe", Desc: "Debug stack frame icon"},
	{Name: "debug-stackframe-active", Desc: "Active debug stack frame icon"},
	{Name: "debug-stackframe-dot", Desc: "Debug stack frame dot icon"},
	{Name: "debug-stackframe-focused", Desc: "Focused debug stack frame icon"},
	{Name: "debug-start", Desc: "Debug start icon"},
	{Name: "debug-step-back", Desc: "Debug step back icon"},
	{Name: "debug-step-into", Desc: "Debug step into icon"},
	{Name: "debug-step-out", Desc: "Debug step out icon"},
	{Name: "debug-step-over", Desc: "Debug step over icon"},
	{Name: "debug-stop", Desc: "Debug stop icon"},
	{Name: "desktop-download", Desc: "Desktop download icon"},
	{Name: "device-camera", Desc: "Device camera icon"},
	{Name: "device-camera-video", Desc: "Device camera video icon"},
	{Name: "device-desktop", Desc: "Desktop device icon"},
	{Name: "device-mobile", Desc: "Mobile device icon"},
	{Name: "diff", Desc: "Diff icon"},
	{Name: "diff-added", Desc: "Diff added icon"},
	{Name: "diff-ignored", Desc: "Diff ignored icon"},
	{Name: "diff-modified", Desc: "Diff modified icon"},
	{Name: "diff-removed", Desc: "Diff removed icon"},
	{Name: "diff-renamed", Desc: "Diff renamed icon"},
	{Name: "discard", Desc: "Discard icon"},
	{Name: "edit", Desc: "Edit icon"},
	{Name: "editor-layout", Desc: "Editor layout icon"},
	{Name: "ellipsis", Desc: "Ellipsis icon"},
	{Name: "empty-window", Desc: "Empty window icon"},
	{Name: "error-small", Desc: "Small error icon"},
	{Name: "error", Desc: "Error icon"},
	{Name: "exclude", Desc: "Exclude icon"},
	{Name: "expand-all", Desc: "Expand all icon"},
	{Name: "export", Desc: "Export icon"},
	{Name: "extensions", Desc: "Extensions icon"},
	{Name: "eye", Desc: "Eye icon"},
	{Name: "eye-closed", Desc: "Eye closed icon"},
	{Name: "eye-unwatch", Desc: "Eye unwatch icon"},
	{Name: "eye-watch", Desc: "Eye watch icon"},
	{Name: "feedback", Desc: "Feedback icon"},
	{Name: "file", Desc: "File icon"},
	{Name: "file-add", Desc: "Add file icon"},
	{Name: "file-binary", Desc: "Binary file icon"},
	{Name: "file-code", Desc: "Code file icon"},
	{Name: "file-directory", Desc: "Directory icon"},
	{Name: "file-directory-create", Desc: "Create directory icon"},
	{Name: "file-media", Desc: "Media file icon"},
	{Name: "file-pdf", Desc: "PDF file icon"},
	{Name: "file-submodule", Desc: "Submodule file icon"},
	{Name: "file-symlink-directory", Desc: "Symlink directory icon"},
	{Name: "file-symlink-file", Desc: "Symlink file icon"},
	{Name: "file-text", Desc: "Text file icon"},
	{Name: "file-zip", Desc: "ZIP file icon"},
	{Name: "files", Desc: "Files icon"},
	{Name: "filter-filled", Desc: "Filled filter icon"},
	{Name: "filter", Desc: "Filter icon"},
	{Name: "flame", Desc: "Flame icon"},
	{Name: "fold", Desc: "Fold icon"},
	{Name: "fold-down", Desc: "Fold down icon"},
	{Name: "fold-up", Desc: "Fold up icon"},
	{Name: "folder", Desc: "Folder icon"},
	{Name: "folder-active", Desc: "Active folder icon"},
	{Name: "folder-library", Desc: "Library folder icon"},
	{Name: "folder-opened", Desc: "Opened folder icon"},
	{Name: "game", Desc: "Game icon"},
	{Name: "gather", Desc: "Gather icon"},
	{Name: "gear", Desc: "Gear icon"},
	{Name: "gift", Desc: "Gift icon"},
	{Name: "gist", Desc: "Gist icon"},
	{Name: "gist-fork", Desc: "Gist fork icon"},
	{Name: "gist-new", Desc: "New gist icon"},
	{Name: "gist-private", Desc: "Private gist icon"},
	{Name: "gist-secret", Desc: "Secret gist icon"},
	{Name: "git-branch", Desc: "Git branch icon"},
	{Name: "git-branch-create", Desc: "Create git branch icon"},
	{Name: "git-branch-delete", Desc: "Delete git branch icon"},
	{Name: "git-commit", Desc: "Git commit icon"},
	{Name: "git-compare", Desc: "Git compare icon"},
	{Name: "git-fetch", Desc: "Git fetch icon"},
	{Name: "git-fork-private", Desc: "Private git fork icon"},
	{Name: "git-merge", Desc: "Git merge icon"},
	{Name: "git-pull-request", Desc: "Git pull request icon"},
	{Name: "git-pull-request-abandoned", Desc: "Abandoned git pull request icon"},
	{Name: "git-pull-request-closed", Desc: "Closed git pull request icon"},
	{Name: "git-pull-request-create", Desc: "Create git pull request icon"},
	{Name: "git-pull-request-draft", Desc: "Draft git pull request icon"},
	{Name: "git-pull-request-new-changes", Desc: "Git pull request new changes icon"},
	{Name: "git-pull-request-go-to-changes", Desc: "Go to git pull request changes icon"},
	{Name: "github", Desc: "GitHub icon"},
	{Name: "github-action", Desc: "GitHub action icon"},
	{Name: "github-alt", Desc: "Alternative GitHub icon"},
	{Name: "github-inverted", Desc: "Inverted GitHub icon"},
	{Name: "globe", Desc: "Globe icon"},
	{Name: "go-to-file", Desc: "Go to file icon"},
	{Name: "grabber", Desc: "Grabber icon"},
	{Name: "graph", Desc: "Graph icon"},
	{Name: "graph-left", Desc: "Left graph icon"},
	{Name: "graph-line", Desc: "Line graph icon"},
	{Name: "graph-scatter", Desc: "Scatter graph icon"},
	{Name: "gripper", Desc: "Gripper icon"},
	{Name: "group-by-ref-type", Desc: "Group by reference type icon"},
	{Name: "heart", Desc: "Heart icon"},
	{Name: "history", Desc: "History icon"},
	{Name: "home", Desc: "Home icon"},
	{Name: "horizontal-rule", Desc: "Horizontal rule icon"},
	{Name: "hubot", Desc: "Hubot icon"},
	{Name: "inbox", Desc: "Inbox icon"},
	{Name: "indent", Desc: "Indent icon"},
	{Name: "info", Desc: "Info icon"},
	{Name: "insert", Desc: "Insert icon"},
	{Name: "inspect", Desc: "Inspect icon"},
	{Name: "issue-closed", Desc: "Closed issue icon"},
	{Name: "issue-draft", Desc: "Draft issue icon"},
	{Name: "issue-opened", Desc: "Opened issue icon"},
	{Name: "issue-reopened", Desc: "Reopened issue icon"},
	{Name: "issues", Desc: "Issues icon"},
	{Name: "italic", Desc: "Italic text icon"},
	{Name: "jersey", Desc: "Jersey icon"},
	{Name: "json", Desc: "JSON icon"},
	{Name: "kebab-horizontal", Desc: "Horizontal kebab icon"},
	{Name: "kebab-vertical", Desc: "Vertical kebab icon"},
	{Name: "key", Desc: "Key icon"},
	{Name: "keyboard", Desc: "Keyboard icon"},
	{Name: "law", Desc: "Law icon"},
	{Name: "layers-active", Desc: "Active layers icon"},
	{Name: "layers-dot", Desc: "Layers dot icon"},
	{Name: "layers", Desc: "Layers icon"},
	{Name: "layout-activitybar-left", Desc: "Activity bar left layout icon"},
	{Name: "layout-activitybar-right", Desc: "Activity bar right layout icon"},
	{Name: "layout-centered", Desc: "Centered layout icon"},
	{Name: "layout-menubar", Desc: "Menu bar layout icon"},
	{Name: "layout-panel-center", Desc: "Panel center layout icon"},
	{Name: "layout-panel-justify", Desc: "Panel justify layout icon"},
	{Name: "layout-panel-left", Desc: "Panel left layout icon"},
	{Name: "layout-panel-right", Desc: "Panel right layout icon"},
	{Name: "layout-panel", Desc: "Panel layout icon"},
	{Name: "layout-sidebar-left", Desc: "Sidebar left layout icon"},
	{Name: "layout-sidebar-right", Desc: "Sidebar right layout icon"},
	{Name: "layout-statusbar", Desc: "Status bar layout icon"},
	{Name: "layout", Desc: "Layout icon"},
	{Name: "library", Desc: "Library icon"},
	{Name: "light-bulb", Desc: "Light bulb icon"},
	{Name: "lightbulb", Desc: "Lightbulb icon"},
	{Name: "lightbulb-autofix", Desc: "Lightbulb autofix icon"},
	{Name: "link", Desc: "Link icon"},
	{Name: "link-external", Desc: "External link icon"},
	{Name: "list-filter", Desc: "List filter icon"},
	{Name: "list-flat", Desc: "Flat list icon"},
	{Name: "list-ordered", Desc: "Ordered list icon"},
	{Name: "list-selection", Desc: "List selection icon"},
	{Name: "list-tree", Desc: "Tree list icon"},
	{Name: "list-unordered", Desc: "Unordered list icon"},
	{Name: "live-share", Desc: "Live share icon"},
	{Name: "loading", Desc: "Loading icon"},
	{Name: "location", Desc: "Location icon"},
	{Name: "lock-small", Desc: "Small lock icon"},
	{Name: "lock", Desc: "Lock icon"},
	{Name: "log-in", Desc: "Log in icon"},
	{Name: "log-out", Desc: "Log out icon"},
	{Name: "logo-github", Desc: "GitHub logo icon"},
	{Name: "magnet", Desc: "Magnet icon"},
	{Name: "mail", Desc: "Mail icon"},
	{Name: "mail-read", Desc: "Read mail icon"},
	{Name: "mail-reply", Desc: "Reply mail icon"},
	{Name: "mark-github", Desc: "GitHub mark icon"},
	{Name: "markdown", Desc: "Markdown icon"},
	{Name: "megaphone", Desc: "Megaphone icon"},
	{Name: "mention", Desc: "Mention icon"},
	{Name: "menu", Desc: "Menu icon"},
	{Name: "merge", Desc: "Merge icon"},
	{Name: "mic", Desc: "Microphone icon"},
	{Name: "mic-filled", Desc: "Filled microphone icon"},
	{Name: "microscope", Desc: "Microscope icon"},
	{Name: "milestone", Desc: "Milestone icon"},
	{Name: "mirror", Desc: "Mirror icon"},
	{Name: "mirror-private", Desc: "Private mirror icon"},
	{Name: "mirror-public", Desc: "Public mirror icon"},
	{Name: "more", Desc: "More icon"},
	{Name: "mortar-board", Desc: "Mortar board icon"},
	{Name: "move", Desc: "Move icon"},
	{Name: "multiple-windows", Desc: "Multiple windows icon"},
	{Name: "music", Desc: "Music icon"},
	{Name: "mute", Desc: "Mute icon"},
	{Name: "new-file", Desc: "New file icon"},
	{Name: "new-folder", Desc: "New folder icon"},
	{Name: "newline", Desc: "Newline icon"},
	{Name: "no-newline", Desc: "No newline icon"},
	{Name: "note", Desc: "Note icon"},
	{Name: "notebook", Desc: "Notebook icon"},
	{Name: "notebook-template", Desc: "Notebook template icon"},
	{Name: "octoface", Desc: "Octoface icon"},
	{Name: "open-preview", Desc: "Open preview icon"},
	{Name: "organization", Desc: "Organization icon"},
	{Name: "organization-filled", Desc: "Filled organization icon"},
	{Name: "organization-outline", Desc: "Organization outline icon"},
	{Name: "output", Desc: "Output icon"},
	{Name: "package", Desc: "Package icon"},
	{Name: "paintcan", Desc: "Paint can icon"},
	{Name: "pass", Desc: "Pass icon"},
	{Name: "pass-filled", Desc: "Filled pass icon"},
	{Name: "pencil", Desc: "Pencil icon"},
	{Name: "person", Desc: "Person icon"},
	{Name: "person-add", Desc: "Add person icon"},
	{Name: "person-filled", Desc: "Filled person icon"},
	{Name: "person-follow", Desc: "Follow person icon"},
	{Name: "person-outline", Desc: "Person outline icon"},
	{Name: "pie-chart", Desc: "Pie chart icon"},
	{Name: "piano", Desc: "Piano icon"},
	{Name: "pin", Desc: "Pin icon"},
	{Name: "pinned", Desc: "Pinned icon"},
	{Name: "pinned-dirty", Desc: "Dirty pinned icon"},
	{Name: "play", Desc: "Play icon"},
	{Name: "play-circle", Desc: "Play circle icon"},
	{Name: "plug", Desc: "Plug icon"},
	{Name: "plus", Desc: "Plus icon"},
	{Name: "preserve-case", Desc: "Preserve case icon"},
	{Name: "preview", Desc: "Preview icon"},
	{Name: "primitive-dot", Desc: "Primitive dot icon"},
	{Name: "primitive-square", Desc: "Primitive square icon"},
	{Name: "project", Desc: "Project icon"},
	{Name: "pulse", Desc: "Pulse icon"},
	{Name: "question", Desc: "Question icon"},
	{Name: "quote", Desc: "Quote icon"},
	{Name: "radio-tower", Desc: "Radio tower icon"},
	{Name: "reactions", Desc: "Reactions icon"},
	{Name: "record", Desc: "Record icon"},
	{Name: "record-keys", Desc: "Record keys icon"},
	{Name: "record-small", Desc: "Small record icon"},
	{Name: "redo", Desc: "Redo icon"},
	{Name: "references", Desc: "References icon"},
	{Name: "refresh", Desc: "Refresh icon"},
	{Name: "regex", Desc: "Regex icon"},
	{Name: "remote", Desc: "Remote icon"},
	{Name: "remote-explorer", Desc: "Remote explorer icon"},
	{Name: "remove", Desc: "Remove icon"},
	{Name: "remove-close", Desc: "Remove close icon"},
	{Name: "repl", Desc: "REPL icon"},
	{Name: "replace", Desc: "Replace icon"},
	{Name: "replace-all", Desc: "Replace all icon"},
	{Name: "reply", Desc: "Reply icon"},
	{Name: "repo", Desc: "Repository icon"},
	{Name: "repo-clone", Desc: "Clone repository icon"},
	{Name: "repo-create", Desc: "Create repository icon"},
	{Name: "repo-delete", Desc: "Delete repository icon"},
	{Name: "repo-force-push", Desc: "Force push repository icon"},
	{Name: "repo-forked", Desc: "Forked repository icon"},
	{Name: "repo-pull", Desc: "Pull repository icon"},
	{Name: "repo-push", Desc: "Push repository icon"},
	{Name: "repo-sync", Desc: "Sync repository icon"},
	{Name: "report", Desc: "Report icon"},
	{Name: "request-changes", Desc: "Request changes icon"},
	{Name: "rocket", Desc: "Rocket icon"},
	{Name: "root-folder", Desc: "Root folder icon"},
	{Name: "root-folder-opened", Desc: "Opened root folder icon"},
	{Name: "rss", Desc: "RSS icon"},
	{Name: "ruby", Desc: "Ruby icon"},
	{Name: "run", Desc: "Run icon"},
	{Name: "run-all", Desc: "Run all icon"},
	{Name: "run-above", Desc: "Run above icon"},
	{Name: "run-below", Desc: "Run below icon"},
	{Name: "run-errors", Desc: "Run errors icon"},
	{Name: "save", Desc: "Save icon"},
	{Name: "save-all", Desc: "Save all icon"},
	{Name: "save-as", Desc: "Save as icon"},
	{Name: "screen-full", Desc: "Full screen icon"},
	{Name: "screen-normal", Desc: "Normal screen icon"},
	{Name: "search", Desc: "Search icon"},
	{Name: "search-save", Desc: "Save search icon"},
	{Name: "search-stop", Desc: "Stop search icon"},
	{Name: "search-fuzzy", Desc: "Fuzzy search icon"},
	{Name: "selection", Desc: "Selection icon"},
	{Name: "send", Desc: "Send icon"},
	{Name: "server", Desc: "Server icon"},
	{Name: "server-environment", Desc: "Server environment icon"},
	{Name: "server-process", Desc: "Server process icon"},
	{Name: "settings", Desc: "Settings icon"},
	{Name: "settings-gear", Desc: "Settings gear icon"},
	{Name: "shield", Desc: "Shield icon"},
	{Name: "sign-in", Desc: "Sign in icon"},
	{Name: "sign-out", Desc: "Sign out icon"},
	{Name: "smiley", Desc: "Smiley icon"},
	{Name: "snake", Desc: "Snake icon"},
	{Name: "sparkle", Desc: "Sparkle icon"},
	{Name: "sort-precedence", Desc: "Sort precedence icon"},
	{Name: "source-control", Desc: "Source control icon"},
	{Name: "split-horizontal", Desc: "Split horizontal icon"},
	{Name: "split-vertical", Desc: "Split vertical icon"},
	{Name: "squirrel", Desc: "Squirrel icon"},
	{Name: "star", Desc: "Star icon"},
	{Name: "star-add", Desc: "Add star icon"},
	{Name: "star-delete", Desc: "Delete star icon"},
	{Name: "star-empty", Desc: "Empty star icon"},
	{Name: "star-full", Desc: "Full star icon"},
	{Name: "star-half", Desc: "Half star icon"},
	{Name: "stop", Desc: "Stop icon"},
	{Name: "stop-circle", Desc: "Stop circle icon"},
	{Name: "symbol-array", Desc: "Array symbol icon"},
	{Name: "symbol-boolean", Desc: "Boolean symbol icon"},
	{Name: "symbol-class", Desc: "Class symbol icon"},
	{Name: "symbol-color", Desc: "Color symbol icon"},
	{Name: "symbol-constant", Desc: "Constant symbol icon"},
	{Name: "symbol-constructor", Desc: "Constructor symbol icon"},
	{Name: "symbol-enum", Desc: "Enum symbol icon"},
	{Name: "symbol-enum-member", Desc: "Enum member symbol icon"},
	{Name: "symbol-event", Desc: "Event symbol icon"},
	{Name: "symbol-field", Desc: "Field symbol icon"},
	{Name: "symbol-file", Desc: "File symbol icon"},
	{Name: "symbol-folder", Desc: "Folder symbol icon"},
	{Name: "symbol-function", Desc: "Function symbol icon"},
	{Name: "symbol-interface", Desc: "Interface symbol icon"},
	{Name: "symbol-key", Desc: "Key symbol icon"},
	{Name: "symbol-keyword", Desc: "Keyword symbol icon"},
	{Name: "symbol-method", Desc: "Method symbol icon"},
	{Name: "symbol-misc", Desc: "Miscellaneous symbol icon"},
	{Name: "symbol-module", Desc: "Module symbol icon"},
	{Name: "symbol-namespace", Desc: "Namespace symbol icon"},
	{Name: "symbol-null", Desc: "Null symbol icon"},
	{Name: "symbol-number", Desc: "Number symbol icon"},
	{Name: "symbol-numeric", Desc: "Numeric symbol icon"},
	{Name: "symbol-object", Desc: "Object symbol icon"},
	{Name: "symbol-operator", Desc: "Operator symbol icon"},
	{Name: "symbol-package", Desc: "Package symbol icon"},
	{Name: "symbol-parameter", Desc: "Parameter symbol icon"},
	{Name: "symbol-property", Desc: "Property symbol icon"},
	{Name: "symbol-reference", Desc: "Reference symbol icon"},
	{Name: "symbol-ruler", Desc: "Ruler symbol icon"},
	{Name: "symbol-snippet", Desc: "Snippet symbol icon"},
	{Name: "symbol-string", Desc: "String symbol icon"},
	{Name: "symbol-struct", Desc: "Struct symbol icon"},
	{Name: "symbol-structure", Desc: "Structure symbol icon"},
	{Name: "symbol-text", Desc: "Text symbol icon"},
	{Name: "symbol-type-parameter", Desc: "Type parameter symbol icon"},
	{Name: "symbol-unit", Desc: "Unit symbol icon"},
	{Name: "symbol-value", Desc: "Value symbol icon"},
	{Name: "symbol-variable", Desc: "Variable symbol icon"},
	{Name: "sync", Desc: "Sync icon"},
	{Name: "sync-ignored", Desc: "Sync ignored icon"},
	{Name: "tag-add", Desc: "Add tag icon"},
	{Name: "tag-remove", Desc: "Remove tag icon"},
	{Name: "tag", Desc: "Tag icon"},
	{Name: "target", Desc: "Target icon"},
	{Name: "tasklist", Desc: "Task list icon"},
	{Name: "telescope", Desc: "Telescope icon"},
	{Name: "terminal-bash", Desc: "Bash terminal icon"},
	{Name: "terminal-cmd", Desc: "CMD terminal icon"},
	{Name: "terminal-debian", Desc: "Debian terminal icon"},
	{Name: "terminal-linux", Desc: "Linux terminal icon"},
	{Name: "terminal-powershell", Desc: "PowerShell terminal icon"},
	{Name: "terminal-tmux", Desc: "Tmux terminal icon"},
	{Name: "terminal-ubuntu", Desc: "Ubuntu terminal icon"},
	{Name: "terminal", Desc: "Terminal icon"},
	{Name: "text-size", Desc: "Text size icon"},
	{Name: "three-bars", Desc: "Three bars icon"},
	{Name: "thumbsdown", Desc: "Thumbs down icon"},
	{Name: "thumbsdown-filled", Desc: "Filled thumbs down icon"},
	{Name: "thumbsup", Desc: "Thumbs up icon"},
	{Name: "thumbsup-filled", Desc: "Filled thumbs up icon"},
	{Name: "tools", Desc: "Tools icon"},
	{Name: "trash", Desc: "Trash icon"},
	{Name: "trashcan", Desc: "Trash can icon"},
	{Name: "triangle-down", Desc: "Triangle down icon"},
	{Name: "triangle-left", Desc: "Triangle left icon"},
	{Name: "triangle-right", Desc: "Triangle right icon"},
	{Name: "triangle-up", Desc: "Triangle up icon"},
	{Name: "twitter", Desc: "Twitter icon"},
	{Name: "type-hierarchy", Desc: "Type hierarchy icon"},
	{Name: "type-hierarchy-sub", Desc: "Type hierarchy sub icon"},
	{Name: "type-hierarchy-super", Desc: "Type hierarchy super icon"},
	{Name: "unfold", Desc: "Unfold icon"},
	{Name: "ungroup-by-ref-type", Desc: "Ungroup by reference type icon"},
	{Name: "unlock", Desc: "Unlock icon"},
	{Name: "unmute", Desc: "Unmute icon"},
	{Name: "unverified", Desc: "Unverified icon"},
	{Name: "variable", Desc: "Variable icon"},
	{Name: "verified-filled", Desc: "Filled verified icon"},
	{Name: "verified", Desc: "Verified icon"},
	{Name: "versions", Desc: "Versions icon"},
	{Name: "vm", Desc: "Virtual machine icon"},
	{Name: "vm-active", Desc: "Active virtual machine icon"},
	{Name: "vm-connect", Desc: "Connect virtual machine icon"},
	{Name: "vm-outline", Desc: "Virtual machine outline icon"},
	{Name: "vm-running", Desc: "Running virtual machine icon"},
	{Name: "vr", Desc: "VR icon"},
	{Name: "warning", Desc: "Warning icon"},
	{Name: "watch", Desc: "Watch icon"},
	{Name: "whitespace", Desc: "Whitespace icon"},
	{Name: "whole-word", Desc: "Whole word icon"},
	{Name: "window", Desc: "Window icon"},
	{Name: "word-wrap", Desc: "Word wrap icon"},
	{Name: "workspace-trusted", Desc: "Trusted workspace icon"},
	{Name: "workspace-unknown", Desc: "Unknown workspace icon"},
	{Name: "workspace-untrusted", Desc: "Untrusted workspace icon"},
	{Name: "wrench", Desc: "Wrench icon"},
	{Name: "wrench-subaction", Desc: "Wrench subaction icon"},
	{Name: "x", Desc: "X icon"},
	{Name: "zap", Desc: "Zap icon"},
	{Name: "zoom-in", Desc: "Zoom in icon"},
	{Name: "zoom-out", Desc: "Zoom out icon"},
}

type VSCodeANSIColor struct {
	Name string
	Desc string
}

func (c VSCodeANSIColor) Title() string       { return c.Name }
func (c VSCodeANSIColor) Description() string { return c.Desc }
func (c VSCodeANSIColor) FilterValue() string { return c.Name }

var VSCodeANSIColors = []VSCodeANSIColor{
	{Name: "terminal.ansiBlack", Desc: "Black"},
	{Name: "terminal.ansiRed", Desc: "Red"},
	{Name: "terminal.ansiGreen", Desc: "Green"},
	{Name: "terminal.ansiYellow", Desc: "Yellow"},
	{Name: "terminal.ansiBlue", Desc: "Blue"},
	{Name: "terminal.ansiMagenta", Desc: "Magenta"},
	{Name: "terminal.ansiCyan", Desc: "Cyan"},
	{Name: "terminal.ansiWhite", Desc: "White"},
	{Name: "terminal.ansiBrightBlack", Desc: "Bright Black"},
	{Name: "terminal.ansiBrightRed", Desc: "Bright Red"},
	{Name: "terminal.ansiBrightGreen", Desc: "Bright Green"},
	{Name: "terminal.ansiBrightYellow", Desc: "Bright Yellow"},
	{Name: "terminal.ansiBrightBlue", Desc: "Bright Blue"},
	{Name: "terminal.ansiBrightMagenta", Desc: "Bright Magenta"},
	{Name: "terminal.ansiBrightCyan", Desc: "Bright Cyan"},
	{Name: "terminal.ansiBrightWhite", Desc: "Bright White"},
}
