package vscode

type Icon struct {
	Name string
	Desc string
}

func (i Icon) Title() string       { return i.Name }
func (i Icon) Description() string { return i.Desc }
func (i Icon) FilterValue() string { return i.Name }

var Icons = []Icon{
	{Name: "$(add)"},
	{Name: "$(archive)"},
	{Name: "$(arrow-both)"},
	{Name: "$(arrow-down)"},
	{Name: "$(arrow-left)"},
	{Name: "$(arrow-right)"},
	{Name: "$(arrow-up)"},
	{Name: "$(bell)"},
	{Name: "$(book)"},
	{Name: "$(bookmark)"},
	{Name: "$(briefcase)"},
	{Name: "$(calendar)"},
	{Name: "$(check)"},
	{Name: "$(chevron-down)"},
	{Name: "$(chevron-left)"},
	{Name: "$(chevron-right)"},
	{Name: "$(chevron-up)"},
	{Name: "$(circle-filled)"},
	{Name: "$(circle-outline)"},
	{Name: "$(clock)"},
	{Name: "$(cloud)"},
	{Name: "$(code)"},
	{Name: "$(comment)"},
	{Name: "$(dashboard)"},
	{Name: "$(database)"},
	{Name: "$(debug)"},
	{Name: "$(device-desktop)"},
	{Name: "$(device-mobile)"},
	{Name: "$(diff)"},
	{Name: "$(discard)"},
	{Name: "$(edit)"},
	{Name: "$(error)"},
	{Name: "$(eye)"},
	{Name: "$(file)"},
	{Name: "$(file-code)"},
	{Name: "$(file-media)"},
	{Name: "$(file-pdf)"},
	{Name: "$(file-submodule)"},
	{Name: "$(file-symlink-file)"},
	{Name: "$(file-text)"},
	{Name: "$(flame)"},
	{Name: "$(folder-opened)"},
	{Name: "$(gear)"},
	{Name: "$(gift)"},
	{Name: "$(git-branch)"},
	{Name: "$(git-commit)"},
	{Name: "$(git-compare)"},
	{Name: "$(git-merge)"},
	{Name: "$(git-pull-request)"},
	{Name: "$(globe)"},
	{Name: "$(go-to-file)"},
	{Name: "$(graph)"},
	{Name: "$(heart)"},
	{Name: "$(history)"},
	{Name: "$(home)"},
	{Name: "$(info)"},
	{Name: "$(issue-opened)"},
	{Name: "$(issue-closed)"},
	{Name: "$(issue-reopened)"},
	{Name: "$(key)"},
	{Name: "$(lightbulb)"},
	{Name: "$(link)"},
	{Name: "$(list-unordered)"},
	{Name: "$(lock)"},
	{Name: "$(mail)"},
	{Name: "$(mark-github)"},
	{Name: "$(mention)"},
	{Name: "$(milestone)"},
	{Name: "$(mirror)"},
	{Name: "$(mortar-board)"},
	{Name: "$(move)"},
	{Name: "$(mute)"},
	{Name: "$(no-newline)"},
	{Name: "$(note)"},
	{Name: "$(octoface)"},
	{Name: "$(organization)"},
	{Name: "$(package)"},
	{Name: "$(paintcan)"},
	{Name: "$(pencil)"},
	{Name: "$(person)"},
	{Name: "$(pin)"},
	{Name: "$(play)"},
	{Name: "$(plug)"},
	{Name: "$(plus)"},
	{Name: "$(primitive-dot)"},
	{Name: "$(primitive-square)"},
	{Name: "$(project)"},
	{Name: "$(pulse)"},
	{Name: "$(question)"},
	{Name: "$(quote)"},
	{Name: "$(radio-tower)"},
	{Name: "$(reply)"},
	{Name: "$(repo)"},
	{Name: "$(repo-clone)"},
	{Name: "$(repo-force-push)"},
	{Name: "$(repo-pull)"},
	{Name: "$(repo-push)"},
	{Name: "$(rocket)"},
	{Name: "$(rss)"},
	{Name: "$(ruby)"},
	{Name: "$(search)"},
	{Name: "$(server)"},
	{Name: "$(settings)"},
	{Name: "$(shield)"},
	{Name: "$(sign-in)"},
	{Name: "$(sign-out)"},
	{Name: "$(smiley)"},
	{Name: "$(sort)"},
	{Name: "$(star)"},
	{Name: "$(stop)"},
	{Name: "$(sync)"},
	{Name: "$(tag)"},
	{Name: "$(tasklist)"},
	{Name: "$(telescope)"},
	{Name: "$(terminal)"},
	{Name: "$(text-size)"},
	{Name: "$(three-bars)"},
	{Name: "$(thumbsdown)"},
	{Name: "$(thumbsup)"},
	{Name: "$(tools)"},
	{Name: "$(trash)"},
	{Name: "$(triangle-down)"},
	{Name: "$(triangle-left)"},
	{Name: "$(triangle-right)"},
	{Name: "$(triangle-up)"},
	{Name: "$(unfold)"},
	{Name: "$(unlock)"},
	{Name: "$(unmute)"},
	{Name: "$(versions)"},
	{Name: "$(vm)"},
	{Name: "$(warning)"},
	{Name: "$(watch)"},
	{Name: "$(zap)"},
}

type ANSIColor struct {
	Name string
	Desc string
}

func (c ANSIColor) Title() string       { return c.Name }
func (c ANSIColor) Description() string { return c.Desc }
func (c ANSIColor) FilterValue() string { return c.Name }

var ANSIColors = []ANSIColor{
	{Name: "terminal.ansiBlack", Desc: "Black"},
	{Name: "terminal.ansiRed", Desc: "Red"},
	{Name: "terminal.ansiGreen", Desc: "Green"},
	{Name: "terminal.ansiYellow", Desc: "Yellow"},
	{Name: "terminal.ansiBlue", Desc: "Blue"},
	{Name: "terminal.ansiMagenta", Desc: "Magenta"},
	{Name: "terminal.ansiCyan", Desc: "Cyan"},
	{Name: "terminal.ansiWhite", Desc: "White"},
	{Name: "terminal.ansiBrightBlack", Desc: "Bright Black"},
	{Name: "terminal.ansiBrightRed", Desc: "Bright Red"},
	{Name: "terminal.ansiBrightGreen", Desc: "Bright Green"},
	{Name: "terminal.ansiBrightYellow", Desc: "Bright Yellow"},
	{Name: "terminal.ansiBrightBlue", Desc: "Bright Blue"},
	{Name: "terminal.ansiBrightMagenta", Desc: "Bright Magenta"},
	{Name: "terminal.ansiBrightCyan", Desc: "Bright Cyan"},
	{Name: "terminal.ansiBrightWhite", Desc: "Bright White"},
}
